"""add purchase invoice tables

Revision ID: 090f81082c52
Revises: b5bed1e44f4d
Create Date: 2026-02-22 17:10:43.018593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090f81082c52'
down_revision: Union[str, Sequence[str], None] = 'b5bed1e44f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_invoice_hdr',
    sa.Column('bill_no', sa.String(length=50), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('vendor_code', sa.String(length=50), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['vendor_code'], ['vendor_master.vendor_code'], ),
    sa.PrimaryKeyConstraint('bill_no')
    )
    op.create_index(op.f('ix_purchase_invoice_hdr_bill_no'), 'purchase_invoice_hdr', ['bill_no'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_hdr_vendor_code'), 'purchase_invoice_hdr', ['vendor_code'], unique=False)
    op.create_table('purchase_invoice_dtl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_no', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bill_no'], ['purchase_invoice_hdr.bill_no'], ),
    sa.ForeignKeyConstraint(['item_code'], ['item_master.item_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_invoice_dtl_bill_no'), 'purchase_invoice_dtl', ['bill_no'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_dtl_id'), 'purchase_invoice_dtl', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_dtl_item_code'), 'purchase_invoice_dtl', ['item_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_invoice_dtl_item_code'), table_name='purchase_invoice_dtl')
    op.drop_index(op.f('ix_purchase_invoice_dtl_id'), table_name='purchase_invoice_dtl')
    op.drop_index(op.f('ix_purchase_invoice_dtl_bill_no'), table_name='purchase_invoice_dtl')
    op.drop_table('purchase_invoice_dtl')
    op.drop_index(op.f('ix_purchase_invoice_hdr_vendor_code'), table_name='purchase_invoice_hdr')
    op.drop_index(op.f('ix_purchase_invoice_hdr_bill_no'), table_name='purchase_invoice_hdr')
    op.drop_table('purchase_invoice_hdr')
    # ### end Alembic commands ###
