"""add vendor master

Revision ID: 3a182d9cfc3a
Revises: e9aeef101c94
Create Date: 2026-02-14 01:42:52.431322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a182d9cfc3a'
down_revision: Union[str, Sequence[str], None] = 'e9aeef101c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_master',
    sa.Column('vendor_code', sa.String(length=50), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('vendor_address_line1', sa.String(length=200), nullable=True),
    sa.Column('vendor_address_line2', sa.String(length=200), nullable=True),
    sa.Column('vendor_address_line3', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('mobile_no', sa.String(length=30), nullable=True),
    sa.Column('ph_no', sa.String(length=30), nullable=True),
    sa.Column('email_id', sa.String(length=200), nullable=True),
    sa.Column('gst_no', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('vendor_code')
    )
    op.create_index(op.f('ix_vendor_master_vendor_code'), 'vendor_master', ['vendor_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_master_vendor_code'), table_name='vendor_master')
    op.drop_table('vendor_master')
    # ### end Alembic commands ###
