"""create item master

Revision ID: 43e4e53a3daa
Revises: f11107e6ec50
Create Date: 2026-02-06 01:25:56.303072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e4e53a3daa'
down_revision: Union[str, Sequence[str], None] = 'f11107e6ec50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_master',
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('item_code')
    )
    op.create_index(op.f('ix_item_master_item_code'), 'item_master', ['item_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_master_item_code'), table_name='item_master')
    op.drop_table('item_master')
    # ### end Alembic commands ###
