"""add sales invoice tables

Revision ID: 45aad675cabd
Revises: 3a182d9cfc3a
Create Date: 2026-02-14 02:04:49.389620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45aad675cabd'
down_revision: Union[str, Sequence[str], None] = '3a182d9cfc3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_invoice_hdr',
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_received', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['customer_code'], ['customer_master.customer_code'], ),
    sa.PrimaryKeyConstraint('invoice_no')
    )
    op.create_index(op.f('ix_sales_invoice_hdr_customer_code'), 'sales_invoice_hdr', ['customer_code'], unique=False)
    op.create_index(op.f('ix_sales_invoice_hdr_invoice_no'), 'sales_invoice_hdr', ['invoice_no'], unique=False)
    op.create_table('sales_invoice_dtl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_no'], ['sales_invoice_hdr.invoice_no'], ),
    sa.ForeignKeyConstraint(['item_code'], ['item_master.item_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_invoice_dtl_id'), 'sales_invoice_dtl', ['id'], unique=False)
    op.create_index(op.f('ix_sales_invoice_dtl_invoice_no'), 'sales_invoice_dtl', ['invoice_no'], unique=False)
    op.create_index(op.f('ix_sales_invoice_dtl_item_code'), 'sales_invoice_dtl', ['item_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_invoice_dtl_item_code'), table_name='sales_invoice_dtl')
    op.drop_index(op.f('ix_sales_invoice_dtl_invoice_no'), table_name='sales_invoice_dtl')
    op.drop_index(op.f('ix_sales_invoice_dtl_id'), table_name='sales_invoice_dtl')
    op.drop_table('sales_invoice_dtl')
    op.drop_index(op.f('ix_sales_invoice_hdr_invoice_no'), table_name='sales_invoice_hdr')
    op.drop_index(op.f('ix_sales_invoice_hdr_customer_code'), table_name='sales_invoice_hdr')
    op.drop_table('sales_invoice_hdr')
    # ### end Alembic commands ###
