"""create customer master

Revision ID: f11107e6ec50
Revises: 
Create Date: 2026-02-06 01:16:19.792992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11107e6ec50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_master',
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_address_line1', sa.String(length=200), nullable=True),
    sa.Column('customer_address_line2', sa.String(length=200), nullable=True),
    sa.Column('customer_address_line3', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('mobile_no', sa.String(length=30), nullable=True),
    sa.Column('ph_no', sa.String(length=30), nullable=True),
    sa.Column('email_id', sa.String(length=200), nullable=True),
    sa.Column('gst_no', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('customer_code')
    )
    op.create_index(op.f('ix_customer_master_customer_code'), 'customer_master', ['customer_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_master_customer_code'), table_name='customer_master')
    op.drop_table('customer_master')
    # ### end Alembic commands ###
